#! /bin/bash

#sudo systemctl stop NetworkManager && sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i wlp2s0 && sudo dhclient wlp2s0


bspc monitor -d 〇 一 二 三 四 五 六 七 八 九

bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color \#121314

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a sayonara state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Conky manage=off


openrazer-daemon &
xsetroot -cursor_name left_ptr &

pgrep -x sxhkd
if [[ $? == 1 ]] 

then
        sxhkd -c .config/bspwm/sxhkdrc &
fi

feh --randomize --bg-fill ~/Immagini/Landscapes &
#wal -i Immagini/Landscapes/ & #& razer-cli -a &
klipper &
dunst &
xrdb ~/.Xresources &
/home/antonino/.config/polybar/launch.sh
xset -dpms s off &
compton --paint-on-overlay --vsync opengl-swc --config .config/compton/compton.conf &
#clight && pkill clight && clight
busctl --expect-reply=false --user set-property org.clight.clight /org/clight/clight/Conf/Backlight org.clight.clight.Conf.Backlight NoAutoCalib "b" false
#picom 
#nmcli device wifi con TIM-50257590 password PASS &
nmtui connect TIM-50257590 && sudo dhclient &
adb tcpip 5555 && adb connect 192.168.1.2

#pgrep -x redshift
#if [[ $? == 1 ]] 
#
#then
#        redshift -t 5500:3000 -b 1.0:0.9 &
#fi

#yakuake &

#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.

#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a yakuake manage=off
